apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  version: {{ kiali.spec_version }}
  auth:
    strategy: openid
    openid:
      client_id: {{ openid.client_id }}
      insecure_skip_verify_tls: true
      issuer_uri: {{ openid.issuer_uri }}
      # Optional explicit endpoints for security-hardened environments
      # authorization_endpoint: {{ openid.authorization_endpoint | default("") }}
      # token_endpoint: {{ openid.token_endpoint | default("") }}
      # userinfo_endpoint: {{ openid.userinfo_endpoint | default("") }}
      # jwks_uri: {{ openid.jwks_uri | default("") }}
      username_claim: {{ openid.username_claim }}
  deployment:
    ingress:
      enabled: false
    logger:
      log_level: trace
    cluster_wide_access: {{ kiali.cluster_wide_access|bool }}
    image_name: "{{ kiali.image_name }}"
    image_pull_policy: {{ kiali.image_pull_policy }}
    image_version: "{{ kiali.image_version }}"
    namespace: {{ kiali.install_namespace }}
    service_type: NodePort
  server:
    node_port: 32080
