apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ kiali_vars.deployment.instance_name }}
  namespace: "{{ kiali_vars.deployment.namespace }}"
  labels: {{ kiali_resource_metadata_labels }}
spec:
{% if kiali_vars.deployment.workload.hpa.spec | length == 0 %}
  replicas: {{ kiali_vars.deployment.workload.replicas }}
{% endif %}
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali
      app.kubernetes.io/instance: {{ kiali_vars.deployment.instance_name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: {{ kiali_vars.deployment.instance_name }}
      labels: {{ kiali_resource_metadata_labels | combine(kiali_vars.deployment.pod.labels) }}
      annotations:
{% if kiali_vars.server.observability.metrics.enabled|bool == True %}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ kiali_vars.server.observability.metrics.port }}"
{% else %}
        prometheus.io/scrape: "false"
        prometheus.io/port: null
{% endif %}
        kiali.io/dashboards: go,kiali
        operator.kiali.io/last-updated: "{{ deployment_last_updated }}"
{% if kiali_vars.deployment.pod.annotations|length > 0 %}
        {{ kiali_vars.deployment.pod.annotations | to_nice_yaml(indent=0) | trim | indent(8) }}
{% endif %}
    spec:
      serviceAccount: {{ kiali_vars.deployment.instance_name }}-service-account
{% if kiali_vars.deployment.pod.priority_class_name != "" %}
      priorityClassName: "{{ kiali_vars.deployment.pod.priority_class_name }}"
{% endif %}
{% if kiali_vars.deployment.image.pull_secrets | default([]) | length > 0 %}
      imagePullSecrets:
{% for n in kiali_vars.deployment.image.pull_secrets %}
      - name: {{ n }}
{% endfor %}
{% endif %}
{% if kiali_vars.deployment.pod.host_aliases|length > 0 %}
      hostAliases:
        {{ kiali_vars.deployment.pod.host_aliases | to_nice_yaml(indent=0) | trim | indent(8) }}
{% endif %}
{% if kiali_vars.deployment.pod.dns | length > 0 %}
{% if kiali_vars.deployment.pod.dns.policy | length > 0 %}
      dnsPolicy: "{{ kiali_vars.deployment.pod.dns.policy }}"
{% endif %}
{% if kiali_vars.deployment.pod.dns.config | length > 0 %}
      dnsConfig:
        {{ kiali_vars.deployment.pod.dns.config | to_nice_yaml(indent=0) | trim | indent(8) }}
{% endif %}
{% endif %}
      containers:
      - image: {{ kiali_vars.deployment.image.name }}{{ '@' + kiali_vars.deployment.image.digest if kiali_vars.deployment.image.digest != '' else '' }}:{{ kiali_vars.deployment.image.version }}
        imagePullPolicy: {{ kiali_vars.deployment.image.pull_policy }}
        name: kiali
        command:
        - "/opt/kiali/kiali"
        - "-config"
        - "/kiali-configuration/config.yaml"
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
{% if kiali_vars.deployment.pod.security_context|length > 0 %}
          {{ kiali_vars.deployment.pod.security_context | to_nice_yaml(indent=0) | trim | indent(10) }}
{% endif %}
{% if kiali_vars.deployment.pod.security_context|length == 0 or lookup('env', 'ALLOW_SECURITY_CONTEXT_OVERRIDE') != "true" %}
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
{% endif %}
        ports:
          - name: api-port
            containerPort: {{ kiali_vars.server.port }}
{% if kiali_vars.server.observability.metrics.enabled|bool == True %}
          - name: http-metrics
            containerPort: {{ kiali_vars.server.observability.metrics.port }}
{% endif %}
        readinessProbe:
          httpGet:
            path: {{ kiali_vars.server.web_root | regex_replace('\\/$', '') }}/healthz
            port: api-port
            scheme:  {{ 'HTTP' if kiali_vars.identity.cert_file == "" else 'HTTPS' }}
          initialDelaySeconds: {{ kiali_vars.deployment.pod.probes.readiness.initial_delay_seconds|int }}
          periodSeconds: {{ kiali_vars.deployment.pod.probes.readiness.period_seconds|int }}
        livenessProbe:
          httpGet:
            path: {{ kiali_vars.server.web_root | regex_replace('\\/$', '') }}/healthz
            port: api-port
            scheme:  {{ 'HTTP' if kiali_vars.identity.cert_file == "" else 'HTTPS' }}
          initialDelaySeconds: {{ kiali_vars.deployment.pod.probes.liveness.initial_delay_seconds|int }}
          periodSeconds: {{ kiali_vars.deployment.pod.probes.liveness.period_seconds|int }}
        startupProbe:
          httpGet:
            path: {{ kiali_vars.server.web_root | regex_replace('\\/$', '') }}/healthz
            port: api-port
            scheme:  {{ 'HTTP' if kiali_vars.identity.cert_file == "" else 'HTTPS' }}
          failureThreshold: {{ kiali_vars.deployment.pod.probes.startup.failure_threshold|int }}
          initialDelaySeconds: {{ kiali_vars.deployment.pod.probes.startup.initial_delay_seconds|int }}
          periodSeconds: {{ kiali_vars.deployment.pod.probes.startup.period_seconds|int }}
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_FORMAT
          value: "{{ kiali_vars.server.observability.logger.log_format }}"
        - name: LOG_LEVEL
          value: "{{ kiali_vars.server.observability.logger.log_level }}"
        - name: LOG_SAMPLER_RATE
          value: "{{ kiali_vars.server.observability.logger.sampler_rate }}"
        - name: LOG_TIME_FIELD_FORMAT
          value: "{{ kiali_vars.server.observability.logger.time_field_format }}"
{% for env in kiali_vars.deployment.pod.custom_envs %}
        - name: "{{ env.name }}"
          value: "{{ env.value }}"
{% endfor %}
        volumeMounts:
        - name: kiali-configuration
          mountPath: "/kiali-configuration"
        - name: kiali-secret
          mountPath: "/kiali-secret"
        - name: kiali-cabundle
          mountPath: "/kiali-cabundle"
{% for sec in kiali_deployment_secret_volumes %}
        - name: {{ sec }}
          mountPath: "/kiali-override-secrets/{{ sec }}"
          readOnly: true
{% endfor %}
{% for secret in kiali_vars.deployment.pod.custom_secrets %}
        - name: {{ secret.name }}
          mountPath: "{{ secret.mount }}"
{% endfor %}
        - name: "kiali-multi-cluster-secret"
          mountPath: "/kiali-remote-cluster-secrets/kiali-multi-cluster-secret"
          readOnly: true
{% for sec in kiali_deployment_remote_cluster_secret_volumes %}
        - name: {{ sec }}
          mountPath: "/kiali-remote-cluster-secrets/{{ kiali_deployment_remote_cluster_secret_volumes[sec].secret_name }}"
          readOnly: true
{% endfor %}
{% if kiali_vars.deployment.pod.resources|length > 0 %}
        resources:
          {{ kiali_vars.deployment.pod.resources | to_nice_yaml(indent=0) | trim | indent(10) }}
{% else %}
        resources: null
{% endif %}
      volumes:
      - name: kiali-configuration
        configMap:
          name: {{ kiali_vars.deployment.instance_name }}
      - name: kiali-secret
        secret:
          secretName: {{ kiali_vars.deployment.secret_name }}
          optional: true
      - name: kiali-cabundle
        configMap:
          name: {{ kiali_vars.deployment.instance_name }}-cabundle
          optional: true
{% for sec in kiali_deployment_secret_volumes %}
      - name: {{ sec }}
        secret:
          secretName: {{ kiali_deployment_secret_volumes[sec].secret_name }}
          items:
          - key: {{ kiali_deployment_secret_volumes[sec].secret_key }}
            path: value.txt
          optional: false
{% endfor %}
{% for secret in kiali_vars.deployment.pod.custom_secrets %}
      - name: {{ secret.name }}
{% if secret.csi is defined %}
        csi:
          {{ secret.csi | to_nice_yaml(indent=0) | trim | indent(10) }}
{% else %}
        secret:
          secretName: {{ secret.name }}
{% if secret.optional is defined %}
          optional: {{ secret.optional }}
{% endif %}
{% endif %}
{% endfor %}
      - name: "kiali-multi-cluster-secret"
        secret:
          secretName: "kiali-multi-cluster-secret"
          optional: true
{% for sec in kiali_deployment_remote_cluster_secret_volumes %}
      - name: {{ sec }}
        secret:
          secretName: {{ kiali_deployment_remote_cluster_secret_volumes[sec].secret_name }}
{% endfor %}
{% if kiali_vars.deployment.pod.affinity.node|length > 0 or kiali_vars.deployment.pod.affinity.pod|length > 0 or kiali_vars.deployment.pod.affinity.pod_anti|length > 0 %}
      affinity:
{% if kiali_vars.deployment.pod.affinity.node|length > 0 %}
        nodeAffinity:
          {{ kiali_vars.deployment.pod.affinity.node | to_nice_yaml(indent=0) | trim | indent(10) }}
{% else %}
        nodeAffinity: null
{% endif %}
{% if kiali_vars.deployment.pod.affinity.pod|length > 0 %}
        podAffinity:
          {{ kiali_vars.deployment.pod.affinity.pod | to_nice_yaml(indent=0) | trim | indent(10) }}
{% else %}
        podAffinity: null
{% endif %}
{% if kiali_vars.deployment.pod.affinity.pod_anti|length > 0 %}
        podAntiAffinity:
          {{ kiali_vars.deployment.pod.affinity.pod_anti | to_nice_yaml(indent=0) | trim | indent(10) }}
{% else %}
        podAntiAffinity: null
{% endif %}
{% else %}
      affinity: null
{% endif %}
{% if kiali_vars.deployment.pod.tolerations|length > 0 %}
      tolerations:
      {{ kiali_vars.deployment.pod.tolerations | to_nice_yaml(indent=0) | trim | indent(6) }}
{% else %}
      tolerations: null
{% endif %}
{% if kiali_vars.deployment.pod.node_selector|length > 0 %}
      nodeSelector:
        {{ kiali_vars.deployment.pod.node_selector | to_nice_yaml(indent=0) | trim | indent(8) }}
{% else %}
      nodeSelector: null
{% endif %}
{% if kiali_vars.deployment.pod.topology_spread_constraints|length > 0 %}
      topologySpreadConstraints:
        {{ kiali_vars.deployment.pod.topology_spread_constraints | to_nice_yaml(indent=0) | trim | indent(8) }}
{% else %}
      topologySpreadConstraints: null
{% endif %}