apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  version: {{ kiali.spec_version }}
  istio_namespace: {{ istio.control_plane_namespace }}
  auth:
    strategy: {{ kiali.auth_strategy }}
  deployment:
    workload:
      replicas: 1
    ingress:
      enabled: true
    image:
      name: "{{ kiali.image_name }}"
      pull_policy: {{ kiali.image_pull_policy }}
      version: "{{ kiali.image_version }}"
    service:
      # while we are here, make sure the additional service yaml retains camelCase
      additional_yaml:
        externalName: my.kiali.example.com
      type: {{ 'LoadBalancer' if is_kind else 'NodePort' }}
    namespace: {{ kiali.install_namespace }}
    # Note that we start with no affinity or tolerations or resources sections,
    # so the first time through we just pick up the defaults.
    cluster_wide_access: {{ kiali.cluster_wide_access|bool }}
  server:
    observability:
      logger:
        log_level: debug
