# Wait for the operator to finish any reconciliation currently ongoing
- import_tasks: ../common/wait_for_kiali_cr_changes.yml

- name: Set affinity and tolerations and resources and pod_annotations and service_annotations and pod_labels in current Kiali CR
  vars:
    current_kiali_cr: "{{ kiali_cr_list.resources[0] }}"
    current_additional_service_yaml: "{{ current_kiali_cr.spec.deployment.service.additional_yaml | default({}) }}"
  set_fact:
    new_kiali_cr: "{{ current_kiali_cr | combine({'spec': {'deployment': {'pod': {'affinity': new_affinity, 'tolerations': new_tolerations, 'resources': new_resources, 'annotations': new_pod_annotations, 'labels': new_pod_labels, 'topology_spread_constraints': new_topology_spread_constraints}, 'service': {'annotations': new_service_annotations, 'additional_yaml': current_additional_service_yaml}, 'workload': {'hpa': new_hpa}, 'ingress': { 'additional_labels': new_ingress_labels }}}}, recursive=True) }}"

- import_tasks: ../common/set_kiali_cr.yml
