- name: Prepare status progress facts
  ignore_errors: yes
  set_fact:
    status_progress_step: "{{ 1 if status_progress_step is not defined else (status_progress_step|int + 1) }}"
    status_progress_start: "{{ ('%Y-%m-%d %H:%M:%S' | strftime) if status_progress_start is not defined else (status_progress_start) }}"

- name: Update CR status progress field with any additional status fields
  ignore_errors: yes
  vars:
    duration: "{{ ('%Y-%m-%d %H:%M:%S' | strftime | to_datetime) - (status_progress_start | to_datetime) }}"
  uri:
    url: "https://{{ lookup('env', 'KUBERNETES_SERVICE_HOST') }}:{{ lookup('env', 'KUBERNETES_SERVICE_PORT_HTTPS') | default(lookup('env', 'KUBERNETES_SERVICE_PORT')) }}/apis/{{ current_cr.apiVersion }}/namespaces/{{ current_cr.metadata.namespace }}/{{ current_cr.kind | lower }}s/{{ current_cr.metadata.name }}/status"
    method: PATCH
    headers:
      Authorization: "Bearer {{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
      Content-Type: "application/merge-patch+json"
    body_format: json
    body:
      status: "{{ status_vars | default({}) | combine({'progress':{'message': status_progress_step + '. ' + status_progress_message, 'duration': duration }}, recursive=True) }}"
    ca_path: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    status_code: [200]
