apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  version: {{ kiali.spec_version }}
  deployment:
    additional_pod_init_containers_yaml:
    - name: init-test-container
      image: registry.access.redhat.com/ubi9/ubi-minimal:latest
      command: ['sh', '-c', 'echo "Init container started" && sleep 3 && echo "Init container completed"']
    - name: istio-proxy-init
      image: registry.access.redhat.com/ubi9/ubi-minimal:latest
      command: ['sh', '-c', 'echo "Second init container started" && sleep 3 && echo "Second init container completed"']
      env:
      - name: "INIT_TEST_VAR"
        value: "test-value"
    cluster_wide_access: {{ kiali.cluster_wide_access|bool }}
    ingress:
      enabled: true
    logger:
      log_level: debug
    namespace: {{ kiali.install_namespace }}
    image_name: "{{ kiali.image_name }}"
    image_pull_policy: {{ kiali.image_pull_policy }}
    image_version: "{{ kiali.image_version }}"
    service_type: {{ 'LoadBalancer' if is_kind else 'NodePort' }}
  server:
    node_port: 32444
