apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  version: {{ kiali.spec_version }}
  deployment:
    cluster_wide_access: {{ kiali.cluster_wide_access|bool }}
    ingress:
      enabled: true
    logger:
      log_level: debug
    namespace: {{ kiali.install_namespace }}
    image_name: "{{ kiali.image_name }}"
    image_pull_policy: {{ kiali.image_pull_policy }}
    image_version: "{{ kiali.image_version }}"
    service_type: {{ 'LoadBalancer' if is_kind else 'NodePort' }}
  external_services:
    grafana:
      dashboards:
      - name: "Istio Service Dashboard"
        variables:
          datasource: "var-datasource"
          namespace: "var-namespace"
          service: "var-service"
          version: "var-version"
      - name: "Istio Workload Dashboard"
        variables:
          datasource: "var-datasource"
          namespace: "var-namespace"
          workload: "var-workload"
          version: "var-version"
    istio:
      istiod_polling_interval_seconds: 20
      validation_change_detection_enabled: true
    perses:
      dashboards:
      - name: "Istio Service Dashboard"
        variables:
          datasource: "var-datasource"
          namespace: "var-namespace"
          service: "var-service"
          version: "var-version"
      - name: "Istio Workload Dashboard"
        variables:
          datasource: "var-datasource"
          namespace: "var-namespace"
          workload: "var-workload"
          version: "var-version"
  istio_labels:
    ambient_namespace_label: "istio.io/dataplane-mode"
    ambient_namespace_label_value: "ambient"
    ambient_waypoint_gateway_label: "gateway.networking.k8s.io/gateway-name"
    ambient_waypoint_label: "gateway.istio.io/managed"
    ambient_waypoint_label_value: "istio.io-mesh-controller"
    ambient_waypoint_use_label: "istio.io/use-waypoint"
  kiali_feature_flags:
    ui_defaults:
      mesh:
        find_options:
        - description: "Find: unhealthy nodes"
          expression: "! healthy"
        hide_options:
        - description: "Hide: healthy nodes"
          expression: "healthy"
  server:
    node_port: 32444
    observability:
      tracing:
        sampling_rate: 0.5
