name: Release Tag Creator

on:
  workflow_dispatch:
    inputs:
      tag_branch:
        description: Branch to tag
        required: true
        default: v2.11
        type: string
      bump_next_version:
        description: Bump to next version after creating release tag
        required: true
        default: true
        type: boolean

jobs:
  release_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.inputs.tag_branch }}
        # We need to fetch the full history to determine the latest tag
        fetch-depth: 0

    - name: Configure git
      run: |
        git config user.email 'kiali-dev@googlegroups.com'
        git config user.name 'kiali-bot'

    - name: Create Release Tag in kiali/kiali-operator
      run: |
        RELEASE_VERSION=$(sed -rn 's/^VERSION \?= (.*)/\1/p' Makefile)

        LATEST_TAG=$(git describe --tags --abbrev=0)

        # Check if the latest tag is the current ossm version tag
        if [[ "$LATEST_TAG" == "$RELEASE_VERSION-ossm" ]]; then
          # Delete the ossm version tag
          echo "Deleting existing ossm version tag: $RELEASE_VERSION-ossm"
          git push origin --delete refs/tags/$RELEASE_VERSION-ossm

          # Create the release tag
          echo "Creating release tag $RELEASE_VERSION"
          git push origin $(git rev-parse HEAD):refs/tags/$RELEASE_VERSION
        else
          echo "Error: Latest tag $LATEST_TAG does not match expected $RELEASE_VERSION-ossm tag"
          exit 1
        fi

  bump_version:
    name: Bump to Next Version
    needs: [release_tag]
    if: ${{ inputs.bump_next_version }}
    uses: ./.github/workflows/bump-release-version.yml
    with:
      tag_branch: ${{ inputs.tag_branch }}
